"""empty message

Revision ID: 1bc04465f4dd
Revises: 19878ac40c86
Create Date: 2022-03-18 20:14:47.540573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bc04465f4dd'
down_revision = '19878ac40c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('char',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('s_name', sa.String(length=75), nullable=False),
    sa.Column('name', sa.String(length=75), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('comic_appearances', sa.String(length=150), nullable=True),
    sa.Column('super_power', sa.String(length=200), nullable=True),
    sa.Column('equipment', sa.String(length=150), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('contributor', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('s_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('char')
    # ### end Alembic commands ###
